#

# Global configuration: update the defines below to match your configuration.
#

AVRTOOL_ROOT    = /usr/local/CrossPack-AVR/bin

ARDUINO_ROOT    = ../../arduino
ARDUINO_VERSION = 100

# Per folder configuration: update to match this application.
#
BOARD   = uno

TARGET  = MPX5xxx
SRC     = MPX5xxx.cpp

include $(ARDUINO_ROOT)/Arduino.mk

# Generated by "make depend"
include .depend
